# Default properties

spring:
  profiles:
    active: cloud

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: beans, health, loggers
    health:
      enabled: true
    loggers:
      enabled: true
    beans:
      enabled: true

# Message Queue specific configs for app1
# app1.exchange.name=app1-exchange
#  app1.queue.name=app1-queue
#  app1.routing.key=app1-routing-key


#AMQP RabbitMQ configuration
# spring.rabbitmq.host:127.0.0.1
# spring.rabbitmq.port:32770
#  spring.rabbitmq.username=guest
#  spring.rabbitmq.password=guest
  # Additional RabbitMQ properties
#  spring.rabbitmq.listener.simple.concurrency=4
#  spring.rabbitmq.listener.simple.max-concurrency=8
#  spring.rabbitmq.listener.simple.retry.initial-interval=5000


---
# Development profile

spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema=my_schema
    username: postgres
    password:
    initialization-mode: always
  jpa:
    generate-ddl: false
    properties:
      eclipselink.target-database: org.eclipse.persistence.platform.database.PostgreSQLPlatform
      eclipselink.jdbc.allow-native-sql-query: true
      eclipselink.logging.parameters: true
      eclipselink.logging.level: FINEST
      eclipselink.weaving: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cache:
    type: redis
  redis:
    host: redis
    port: 6379

logging.level.root: INFO
logging.level.org.springframework.cloud.sleuth: DEBUG
spring.cloud.refresh.refreshable: none

---
# Integration test profile

spring:
  profiles: integration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=my_schema
    username: postgres
    password:
    initialization-mode: always
  jpa:
    generate-ddl: false
    properties:
      eclipselink.target-database: org.eclipse.persistence.platform.database.PostgreSQLPlatform
      eclipselink.jdbc.allow-native-sql-query: true
      eclipselink.logging.parameters: true
      eclipselink.logging.level: FINEST
      eclipselink.weaving: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

---
# Cloud profile

spring:
  profiles: cloud
  datasource:
    initialization-mode: always
  jpa:
    generate-ddl: false
    properties:
      eclipselink.target-database: org.eclipse.persistence.platform.database.PostgreSQLPlatform
      eclipselink.jdbc.allow-native-sql-query: true
      eclipselink.logging.parameters: true
      eclipselink.logging.level: FINEST
      eclipselink.weaving: false