# Default properties
logging:
  level:
    ROOT: DEBUG

---
# Development profile
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:32768/postgres?searchpath=my_schema
    username: postgres
    password:
    initialization-mode: always
  jpa:
    generate-ddl: false
    properties:
      eclipselink.target-database: org.eclipse.persistence.platform.database.PostgreSQLPlatform
      eclipselink.jdbc.allow-native-sql-query: true
      eclipselink.logging.parameters: true
      eclipselink.logging.level: FINEST
      eclipselink.weaving: false

---
## Integration test profile
spring:
  profiles: integration
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:m8b
  jpa:
    generate-ddl: false
    properties:
      eclipselink.target-database: org.eclipse.persistence.platform.database.H2Platform
      eclipselink.jdbc.allow-native-sql-query: true
      eclipselink.logging.parameters: true
      eclipselink.logging.level: FINEST
      eclipselink.weaving: false
  h2:
    console:
      enabled: true